package models

import (
	"time"

	"github.com/google/uuid"
)

// Summary represents structured analytical meeting intelligence generated by LLM engines.
type Summary struct {
	ID               uuid.UUID  `gorm:"type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	RecordingID      uuid.UUID  `gorm:"type:uuid;not null;index:idx_summaries_recording_active,priority:1;index:idx_summaries_version,priority:1" json:"recording_id"`
	Recording        *Recording `gorm:"foreignKey:RecordingID;constraint:OnDelete:CASCADE" json:"recording,omitempty"`
	TemplateCategory string     `gorm:"type:varchar(100);not null" json:"template_category"`
	CustomAngle      *string    `gorm:"type:text" json:"custom_angle,omitempty"`
	Version          int        `gorm:"not null;default:1;index:idx_summaries_version,priority:2" json:"version"`
	IsActive         bool       `gorm:"not null;default:true;index:idx_summaries_recording_active,priority:2" json:"is_active"`
	StructuredData   JSONMap    `gorm:"type:jsonb;not null;default:'{}'" json:"structured_data"`
	MarkdownContent  string     `gorm:"type:text;not null;default:''" json:"markdown_content"`
	CreatedAt        time.Time  `gorm:"not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time  `gorm:"not null;default:now()" json:"updated_at"`
}

func (Summary) TableName() string {
	return "summaries"
}
